version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./frontend.Dockerfile
    container_name: vad-analysis-app
    ports:
      - "3000:3000"
    environment:
      - JWT_SECRET=secret-vad-analysis-platform-key-2026-docker
      - NODE_ENV=production
      - DATA_DIR=/app/data
    volumes:
      - ./data:/app/data
    restart: always

